create add_coordinate_uncertainty
b-cubed-eu/simcuber pull request #20
Opened 2024-04-03 09:58 UTC by avrodrigues

Create the function to add a new column to an sf object with POINT geometry. 
There is an initial documentation for the function

2024-04-03 10:16 UTC, PietrH requested changes

2024-04-03 10:16 UTC, PietrH commented on R/add_coordinate_uncertainty.R
> +#'   coordinate_uncertainty_meters = rgamma(n_points, shape = 5, rate = 0.1)
The argument has a different name in the examples than it does in the function definition, causing the examples to fail.

2024-04-03 10:19 UTC, wlangera requested changes
please use the cli package for testing and use importfrom instead of importing the full package as discussed in real life :)

2024-04-03 10:32 UTC, PietrH commented
codecov also seems to think some lines are not covered by tests

2024-04-03 12:49 UTC, wlangera commented
@micdimu can you check this out and add your code/comments where relevant?

2024-04-04 06:35 UTC, wlangera commented
I just realised that it is maybe better to not use this function as a helper within `sample_observations()` since it is not known a priori how many observations will be there so the user cannot know how long his/her vector should be if he/she wants to set an uncertainty for each observation.

Maybe this should be a separate function to be used after `sample_observations()`? This would mostly influence the documentation, so no big issue. Maybe talk about this today.

2024-04-04 10:39 UTC, PietrH commented
I've added unit tests, and changed some style things. Also added an extra assertion for the coords in meters argument. 

One test still missing, I added an emtpy test as a reminder, but will probably not get to it this hackathon.

2024-04-04 12:48 UTC, PietrH approved these changes

2024-04-04 12:49 UTC, wlangera approved these changes

2024-04-04 12:55 UTC, ToonVanDaele commented
Add coordinate_uncertainty

2024-04-04 12:56 UTC, merged

2024-04-04 12:56 UTC, ToonVanDaele commented
add_coords_uncertainty